export type Gender = "M" | "F";
export type Urgency = "normal" | "high" | "critical";
export type Availability = "immediate" | "today" | "tomorrow" | "this_week";

export interface TimeSlot {
  date: string;       // ISO date string
  time: string;       // "HH:MM"
  label: string;      // human-friendly e.g. "Today, 2:30 PM"
}

export interface Doctor {
  id: string;
  name: string;
  initials: string;
  specialty: string;
  subspecialty: string;
  gender: Gender;
  languages: string[];
  insuranceAccepted: string[];
  availableSlots: TimeSlot[];
  nextAvailable: Availability;
  rating: number;           // 1–5
  reviewCount: number;
  yearsExperience: number;
  qualifications: string[];
  hospital: string;
  department: string;
  keywords: string[];       // symptom/condition keywords for scoring
  urgencyCapable: boolean;  // can handle high/critical cases
  emergencySpecialist: boolean;
  bio: string;
  consultationFee: number;  // INR
  acceptsWalkIn: boolean;
}

// ---------------------------------------------------------------------------
// Hardcoded doctor database — replace with DB queries in production
// ---------------------------------------------------------------------------

export const DOCTORS: Doctor[] = [
  {
    id: "dr-001",
    name: "Dr. Priya Sharma",
    initials: "PS",
    specialty: "General Surgery",
    subspecialty: "GI & Abdominal Surgery",
    gender: "F",
    languages: ["English", "Hindi", "Bengali"],
    insuranceAccepted: ["Star Health", "HDFC ERGO", "CGHS", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "14:30", label: "Today, 2:30 PM" },
      { date: new Date().toISOString().split("T")[0], time: "17:00", label: "Today, 5:00 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "10:00",
        label: "Tomorrow, 10:00 AM",
      },
    ],
    nextAvailable: "today",
    rating: 4.8,
    reviewCount: 142,
    yearsExperience: 14,
    qualifications: ["MS (Surgery)", "FRCS", "FIAGES"],
    hospital: "Apollo Gleneagles Hospital",
    department: "Surgical Sciences",
    keywords: [
      "abdominal", "abdomen", "stomach", "pain", "appendix", "appendicitis",
      "hernia", "bowel", "intestine", "right side", "lower right", "nausea",
      "vomiting", "gallbladder", "gallstone", "bile", "colon", "rectal",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Sharma specializes in minimally invasive abdominal surgery with over 2,000 laparoscopic procedures. She leads the GI Surgery unit at Apollo Gleneagles.",
    consultationFee: 1200,
    acceptsWalkIn: false,
  },
  {
    id: "dr-002",
    name: "Dr. Arjun Mehta",
    initials: "AM",
    specialty: "Cardiology",
    subspecialty: "Interventional Cardiology",
    gender: "M",
    languages: ["English", "Hindi", "Bengali"],
    insuranceAccepted: ["CGHS", "Star Health", "Niva Bupa", "HDFC ERGO", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "10:00",
        label: "Tomorrow, 10:00 AM",
      },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "15:30",
        label: "Tomorrow, 3:30 PM",
      },
    ],
    nextAvailable: "tomorrow",
    rating: 4.9,
    reviewCount: 231,
    yearsExperience: 18,
    qualifications: ["DM (Cardiology)", "FESC", "FACC"],
    hospital: "Fortis Hospital",
    department: "Cardiology & Cardiac Sciences",
    keywords: [
      "chest", "heart", "cardiac", "shortness of breath", "breathless",
      "palpitation", "palpitations", "blood pressure", "hypertension",
      "angina", "ECG", "irregular heartbeat", "tightness", "pressure",
      "radiating", "left arm", "jaw pain", "sweating", "fatigue",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Mehta is a top-ranked interventional cardiologist with expertise in complex coronary interventions and structural heart disease.",
    consultationFee: 1500,
    acceptsWalkIn: false,
  },
  {
    id: "dr-003",
    name: "Dr. Sneha Roy",
    initials: "SR",
    specialty: "Neurology",
    subspecialty: "Headache & Migraine Medicine",
    gender: "F",
    languages: ["English", "Bengali"],
    insuranceAccepted: ["HDFC ERGO", "Niva Bupa", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "17:00", label: "Today, 5:00 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "11:00",
        label: "Tomorrow, 11:00 AM",
      },
    ],
    nextAvailable: "today",
    rating: 4.7,
    reviewCount: 98,
    yearsExperience: 10,
    qualifications: ["DM (Neurology)", "PDF (Headache Medicine, Mayo Clinic)"],
    hospital: "AMRI Hospitals",
    department: "Neurosciences",
    keywords: [
      "headache", "migraine", "head pain", "vision", "blurred vision",
      "dizziness", "vertigo", "numbness", "tingling", "seizure", "epilepsy",
      "memory", "confusion", "weakness", "tremor", "balance", "coordination",
      "neurological", "stroke", "TIA",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Roy is a specialist in headache disorders and neurovascular conditions, trained at Mayo Clinic. She runs a dedicated headache clinic.",
    consultationFee: 1000,
    acceptsWalkIn: false,
  },
  {
    id: "dr-004",
    name: "Dr. Vikram Patel",
    initials: "VP",
    specialty: "Orthopedics",
    subspecialty: "Sports Medicine & Joint Reconstruction",
    gender: "M",
    languages: ["English", "Hindi", "Gujarati"],
    insuranceAccepted: ["Star Health", "CGHS", "HDFC ERGO", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "15:45", label: "Today, 3:45 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "09:30",
        label: "Tomorrow, 9:30 AM",
      },
    ],
    nextAvailable: "today",
    rating: 4.6,
    reviewCount: 187,
    yearsExperience: 12,
    qualifications: ["MS (Ortho)", "MCh (Joint Reconstruction)", "FASM"],
    hospital: "Medica Superspecialty Hospital",
    department: "Orthopedics & Sports Medicine",
    keywords: [
      "knee", "knee pain", "joint", "joints", "bone", "fracture", "broken",
      "sports", "injury", "sprain", "ligament", "ACL", "meniscus",
      "shoulder", "hip", "back pain", "spine", "disc", "slip disc",
      "swelling", "stiffness", "arthritis", "cartilage",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Patel is a fellowship-trained joint reconstruction and sports medicine surgeon, having operated on professional athletes across India.",
    consultationFee: 1100,
    acceptsWalkIn: true,
  },
  {
    id: "dr-005",
    name: "Dr. Amina Khan",
    initials: "AK",
    specialty: "Endocrinology",
    subspecialty: "Diabetes & Thyroid Disorders",
    gender: "F",
    languages: ["English", "Bengali", "Hindi", "Urdu"],
    insuranceAccepted: ["HDFC ERGO", "Star Health", "Niva Bupa", "CGHS", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "11:30",
        label: "Tomorrow, 11:30 AM",
      },
      {
        date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
        time: "14:00",
        label: "Day after, 2:00 PM",
      },
    ],
    nextAvailable: "tomorrow",
    rating: 4.8,
    reviewCount: 163,
    yearsExperience: 11,
    qualifications: ["DM (Endocrinology)", "FRCP (London)", "CDE"],
    hospital: "Ruby General Hospital",
    department: "Endocrinology & Metabolism",
    keywords: [
      "diabetes", "diabetic", "HbA1c", "blood sugar", "sugar", "insulin",
      "thyroid", "hypothyroid", "hyperthyroid", "TSH", "T3", "T4",
      "weight gain", "weight loss", "fatigue", "hormones", "hormone",
      "PCOS", "polycystic", "Cushing", "Addison", "adrenal",
    ],
    urgencyCapable: false,
    emergencySpecialist: false,
    bio: "Dr. Khan is a consultant endocrinologist with special expertise in complex diabetes management and thyroid malignancy.",
    consultationFee: 1300,
    acceptsWalkIn: false,
  },
  {
    id: "dr-006",
    name: "Dr. Rajesh Nair",
    initials: "RN",
    specialty: "Emergency Medicine",
    subspecialty: "Acute & Trauma Care",
    gender: "M",
    languages: ["English", "Hindi", "Malayalam"],
    insuranceAccepted: [
      "Star Health", "HDFC ERGO", "Niva Bupa", "CGHS", "Self-pay", "All insurance accepted",
    ],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "00:00", label: "Immediate" },
    ],
    nextAvailable: "immediate",
    rating: 4.9,
    reviewCount: 412,
    yearsExperience: 16,
    qualifications: ["MD (Emergency Medicine)", "FCEM", "ATLS Instructor"],
    hospital: "Apollo Gleneagles Hospital",
    department: "Emergency & Trauma",
    keywords: [
      "severe", "emergency", "acute", "sudden", "trauma", "accident",
      "unconscious", "unresponsive", "breathing", "cant breathe",
      "can't breathe", "crushing", "worst", "dying", "faint", "collapse",
    ],
    urgencyCapable: true,
    emergencySpecialist: true,
    bio: "Dr. Nair heads the 24/7 Emergency & Trauma unit. He is an ATLS instructor and has managed over 10,000 emergency cases.",
    consultationFee: 0,
    acceptsWalkIn: true,
  },
  {
    id: "dr-007",
    name: "Dr. Meera Iyer",
    initials: "MI",
    specialty: "Pulmonology",
    subspecialty: "Respiratory & Sleep Medicine",
    gender: "F",
    languages: ["English", "Tamil", "Hindi"],
    insuranceAccepted: ["Star Health", "Niva Bupa", "HDFC ERGO", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "16:00", label: "Today, 4:00 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "12:00",
        label: "Tomorrow, 12:00 PM",
      },
    ],
    nextAvailable: "today",
    rating: 4.7,
    reviewCount: 117,
    yearsExperience: 9,
    qualifications: ["DM (Pulmonology)", "PDF (Sleep Medicine)", "FCCP"],
    hospital: "Peerless Hospital",
    department: "Pulmonology & Critical Care",
    keywords: [
      "breathing", "breathless", "shortness of breath", "cough", "chronic cough",
      "asthma", "COPD", "lung", "wheeze", "wheezing", "sleep apnea",
      "snoring", "TB", "tuberculosis", "pneumonia", "bronchitis",
      "oxygen", "sputum", "respiratory",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Iyer is a leading pulmonologist with a subspecialty in sleep-disordered breathing and asthma management.",
    consultationFee: 900,
    acceptsWalkIn: false,
  },
  {
    id: "dr-008",
    name: "Dr. Saurav Das",
    initials: "SD",
    specialty: "Gastroenterology",
    subspecialty: "Hepatology & IBD",
    gender: "M",
    languages: ["English", "Bengali", "Hindi"],
    insuranceAccepted: ["CGHS", "Star Health", "HDFC ERGO", "Niva Bupa", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "09:00",
        label: "Tomorrow, 9:00 AM",
      },
    ],
    nextAvailable: "tomorrow",
    rating: 4.8,
    reviewCount: 204,
    yearsExperience: 15,
    qualifications: ["DM (Gastroenterology)", "MRCP (UK)", "FASGE"],
    hospital: "Belle Vue Clinic",
    department: "Gastroenterology & Hepatology",
    keywords: [
      "acidity", "acid reflux", "GERD", "gastric", "ulcer", "liver",
      "hepatitis", "jaundice", "yellow eyes", "yellow skin",
      "IBD", "Crohn", "colitis", "diarrhea", "constipation",
      "bloating", "stomach pain", "abdominal", "endoscopy", "colonoscopy",
    ],
    urgencyCapable: false,
    emergencySpecialist: false,
    bio: "Dr. Das is a senior gastroenterologist with deep expertise in inflammatory bowel disease and advanced endoscopic procedures.",
    consultationFee: 1400,
    acceptsWalkIn: false,
  },
  {
    id: "dr-009",
    name: "Dr. Kavita Menon",
    initials: "KM",
    specialty: "Dermatology",
    subspecialty: "Cosmetic & Clinical Dermatology",
    gender: "F",
    languages: ["English", "Tamil", "Hindi", "Malayalam"],
    insuranceAccepted: ["Star Health", "HDFC ERGO", "Niva Bupa", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "13:00", label: "Today, 1:00 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "10:30",
        label: "Tomorrow, 10:30 AM",
      },
    ],
    nextAvailable: "today",
    rating: 4.7,
    reviewCount: 176,
    yearsExperience: 11,
    qualifications: ["MD (Dermatology)", "DNB", "FAAD"],
    hospital: "AMRI Hospitals",
    department: "Dermatology & Cosmetology",
    keywords: [
      "skin", "rash", "itching", "itch", "acne", "pimple", "eczema",
      "psoriasis", "hives", "urticaria", "allergy", "allergic reaction",
      "hair loss", "alopecia", "dandruff", "fungal", "ringworm", "wart",
      "mole", "pigmentation", "dark spots", "sunburn", "dry skin",
    ],
    urgencyCapable: false,
    emergencySpecialist: false,
    bio: "Dr. Menon is a dual-trained clinical and cosmetic dermatologist with special interest in acne management, hair disorders, and laser therapy.",
    consultationFee: 800,
    acceptsWalkIn: false,
  },
  {
    id: "dr-010",
    name: "Dr. Rohan Ghosh",
    initials: "RG",
    specialty: "Psychiatry",
    subspecialty: "Adult Psychiatry & Psychotherapy",
    gender: "M",
    languages: ["English", "Bengali", "Hindi"],
    insuranceAccepted: ["HDFC ERGO", "Niva Bupa", "CGHS", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "14:00",
        label: "Tomorrow, 2:00 PM",
      },
      {
        date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
        time: "11:00",
        label: "Day after, 11:00 AM",
      },
    ],
    nextAvailable: "tomorrow",
    rating: 4.9,
    reviewCount: 134,
    yearsExperience: 13,
    qualifications: ["MD (Psychiatry)", "DNB", "MRCPsych (UK)"],
    hospital: "Fortis Hospital",
    department: "Mental Health & Behavioral Sciences",
    keywords: [
      "anxiety", "depression", "mental health", "stress", "panic attack",
      "panic", "mood", "bipolar", "schizophrenia", "OCD", "PTSD",
      "insomnia", "sleep", "phobia", "eating disorder", "addiction",
      "substance abuse", "suicidal", "self harm", "grief", "burnout",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Ghosh is a consultant psychiatrist trained in the UK with expertise in mood disorders, anxiety, and trauma-focused therapy.",
    consultationFee: 1500,
    acceptsWalkIn: false,
  },
  {
    id: "dr-011",
    name: "Dr. Sunita Bose",
    initials: "SB",
    specialty: "Obstetrics & Gynecology",
    subspecialty: "High-Risk Pregnancy & Reproductive Medicine",
    gender: "F",
    languages: ["English", "Bengali", "Hindi"],
    insuranceAccepted: ["Star Health", "HDFC ERGO", "CGHS", "Niva Bupa", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "11:00", label: "Today, 11:00 AM" },
      { date: new Date().toISOString().split("T")[0], time: "16:30", label: "Today, 4:30 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "09:00",
        label: "Tomorrow, 9:00 AM",
      },
    ],
    nextAvailable: "today",
    rating: 4.8,
    reviewCount: 289,
    yearsExperience: 17,
    qualifications: ["MS (Obs & Gynae)", "FRCOG", "FICOG"],
    hospital: "Apollo Gleneagles Hospital",
    department: "Obstetrics, Gynaecology & Reproductive Medicine",
    keywords: [
      "pregnancy", "pregnant", "menstrual", "period", "irregular periods",
      "PCOS", "polycystic ovary", "fertility", "infertility", "IVF",
      "vaginal discharge", "pelvic pain", "menopause", "fibroids",
      "ovarian cyst", "cervical", "uterus", "gynecology", "contraception",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Bose is a senior obstetrician-gynecologist with 17 years managing high-risk pregnancies and complex gynecological conditions.",
    consultationFee: 1200,
    acceptsWalkIn: false,
  },
  {
    id: "dr-012",
    name: "Dr. Partho Sengupta",
    initials: "PS",
    specialty: "Nephrology",
    subspecialty: "Chronic Kidney Disease & Dialysis",
    gender: "M",
    languages: ["English", "Bengali", "Hindi"],
    insuranceAccepted: ["CGHS", "Star Health", "HDFC ERGO", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "10:00",
        label: "Tomorrow, 10:00 AM",
      },
      {
        date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
        time: "15:00",
        label: "Day after, 3:00 PM",
      },
    ],
    nextAvailable: "tomorrow",
    rating: 4.7,
    reviewCount: 158,
    yearsExperience: 14,
    qualifications: ["DM (Nephrology)", "MRCP (UK)", "FASN"],
    hospital: "Medica Superspecialty Hospital",
    department: "Nephrology & Renal Transplant",
    keywords: [
      "kidney", "renal", "dialysis", "creatinine", "urine", "urination",
      "blood in urine", "swelling", "edema", "water retention",
      "kidney stone", "kidney failure", "UTI", "urinary tract infection",
      "protein in urine", "nephrotic", "polycystic kidney",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Sengupta is a consultant nephrologist specializing in CKD management, renal replacement therapy, and post-transplant care.",
    consultationFee: 1200,
    acceptsWalkIn: false,
  },
  {
    id: "dr-013",
    name: "Dr. Ananya Chatterjee",
    initials: "AC",
    specialty: "Ophthalmology",
    subspecialty: "Retina & Vitreous Surgery",
    gender: "F",
    languages: ["English", "Bengali"],
    insuranceAccepted: ["Star Health", "HDFC ERGO", "Niva Bupa", "CGHS", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "12:00", label: "Today, 12:00 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "14:30",
        label: "Tomorrow, 2:30 PM",
      },
    ],
    nextAvailable: "today",
    rating: 4.8,
    reviewCount: 211,
    yearsExperience: 12,
    qualifications: ["MS (Ophthalmology)", "DNB", "FVRS"],
    hospital: "Disha Eye Hospitals",
    department: "Ophthalmology & Vitreo-Retinal Services",
    keywords: [
      "eye", "eyes", "vision", "blurred vision", "blurry", "eyesight",
      "red eye", "eye pain", "floaters", "flashes", "cataract",
      "glaucoma", "retina", "macular", "diabetic retinopathy",
      "dry eye", "watery eye", "double vision", "night blindness",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Chatterjee is a vitreo-retinal surgeon with expertise in diabetic eye disease, macular degeneration, and complex retinal detachments.",
    consultationFee: 1000,
    acceptsWalkIn: false,
  },
  {
    id: "dr-014",
    name: "Dr. Suresh Krishnamurthy",
    initials: "SK",
    specialty: "ENT",
    subspecialty: "Head & Neck Surgery",
    gender: "M",
    languages: ["English", "Tamil", "Kannada", "Hindi"],
    insuranceAccepted: ["Star Health", "CGHS", "HDFC ERGO", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "15:00", label: "Today, 3:00 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "11:30",
        label: "Tomorrow, 11:30 AM",
      },
    ],
    nextAvailable: "today",
    rating: 4.6,
    reviewCount: 143,
    yearsExperience: 16,
    qualifications: ["MS (ENT)", "DNB", "FACS"],
    hospital: "Peerless Hospital",
    department: "ENT & Head-Neck Surgery",
    keywords: [
      "ear", "hearing loss", "hearing", "tinnitus", "ringing in ear",
      "nose", "nasal", "blocked nose", "sinusitis", "sinus",
      "throat", "sore throat", "tonsil", "tonsillitis", "voice",
      "hoarseness", "snoring", "adenoid", "dizziness", "vertigo",
    ],
    urgencyCapable: false,
    emergencySpecialist: false,
    bio: "Dr. Krishnamurthy is a senior ENT surgeon with expertise in functional endoscopic sinus surgery and head & neck oncology.",
    consultationFee: 900,
    acceptsWalkIn: true,
  },
  {
    id: "dr-015",
    name: "Dr. Nandita Joshi",
    initials: "NJ",
    specialty: "Oncology",
    subspecialty: "Medical Oncology & Hematology",
    gender: "F",
    languages: ["English", "Hindi", "Marathi"],
    insuranceAccepted: ["Star Health", "HDFC ERGO", "CGHS", "Niva Bupa", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "10:00",
        label: "Tomorrow, 10:00 AM",
      },
      {
        date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
        time: "14:00",
        label: "Day after, 2:00 PM",
      },
    ],
    nextAvailable: "tomorrow",
    rating: 4.9,
    reviewCount: 196,
    yearsExperience: 15,
    qualifications: ["DM (Medical Oncology)", "MRCP (UK)", "ESMO Certified"],
    hospital: "Tata Medical Center",
    department: "Medical Oncology & Hematology",
    keywords: [
      "cancer", "tumor", "lump", "mass", "chemotherapy", "chemo",
      "lymphoma", "leukemia", "blood cancer", "breast cancer",
      "lung cancer", "colon cancer", "unexplained weight loss",
      "night sweats", "fatigue", "anaemia", "anemia", "biopsy",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Joshi is a consultant medical oncologist at Tata Medical Center with expertise in GI cancers, lymphoma, and precision oncology.",
    consultationFee: 2000,
    acceptsWalkIn: false,
  },
  {
    id: "dr-016",
    name: "Dr. Farhan Siddiqui",
    initials: "FS",
    specialty: "Urology",
    subspecialty: "Uro-Oncology & Minimally Invasive Urology",
    gender: "M",
    languages: ["English", "Hindi", "Urdu", "Bengali"],
    insuranceAccepted: ["CGHS", "Star Health", "HDFC ERGO", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "13:00",
        label: "Tomorrow, 1:00 PM",
      },
    ],
    nextAvailable: "tomorrow",
    rating: 4.7,
    reviewCount: 167,
    yearsExperience: 13,
    qualifications: ["MCh (Urology)", "DNB", "FICS"],
    hospital: "Fortis Hospital",
    department: "Urology & Renal Sciences",
    keywords: [
      "urine", "urination", "frequent urination", "painful urination",
      "burning urination", "prostate", "bladder", "kidney stone",
      "blood in urine", "hematuria", "urinary incontinence",
      "erectile dysfunction", "male fertility", "testicular pain",
      "enlarged prostate", "BPH", "urinary retention",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Siddiqui is a urologist specializing in laparoscopic and robotic urological surgeries, with particular expertise in kidney stone disease.",
    consultationFee: 1300,
    acceptsWalkIn: false,
  },
  {
    id: "dr-017",
    name: "Dr. Leela Krishnan",
    initials: "LK",
    specialty: "Rheumatology",
    subspecialty: "Autoimmune & Inflammatory Arthritis",
    gender: "F",
    languages: ["English", "Tamil", "Telugu", "Hindi"],
    insuranceAccepted: ["HDFC ERGO", "Star Health", "Niva Bupa", "CGHS", "Self-pay"],
    availableSlots: [
      {
        date: new Date(Date.now() + 172800000).toISOString().split("T")[0],
        time: "10:00",
        label: "Day after, 10:00 AM",
      },
    ],
    nextAvailable: "this_week",
    rating: 4.8,
    reviewCount: 121,
    yearsExperience: 10,
    qualifications: ["DM (Rheumatology)", "MRCP (UK)", "FACR"],
    hospital: "Apollo Gleneagles Hospital",
    department: "Rheumatology & Clinical Immunology",
    keywords: [
      "joint pain", "joints", "arthritis", "rheumatoid", "lupus",
      "SLE", "autoimmune", "stiffness", "morning stiffness",
      "swollen joints", "gout", "uric acid", "ankylosing spondylitis",
      "fibromyalgia", "vasculitis", "Sjogren", "myositis",
    ],
    urgencyCapable: false,
    emergencySpecialist: false,
    bio: "Dr. Krishnan is a consultant rheumatologist with special expertise in early inflammatory arthritis, lupus, and biologics therapy.",
    consultationFee: 1400,
    acceptsWalkIn: false,
  },
  {
    id: "dr-018",
    name: "Dr. Tarun Biswas",
    initials: "TB",
    specialty: "Pediatrics",
    subspecialty: "Pediatric Medicine & Neonatology",
    gender: "M",
    languages: ["English", "Bengali", "Hindi"],
    insuranceAccepted: ["Star Health", "CGHS", "HDFC ERGO", "Niva Bupa", "Self-pay"],
    availableSlots: [
      { date: new Date().toISOString().split("T")[0], time: "10:00", label: "Today, 10:00 AM" },
      { date: new Date().toISOString().split("T")[0], time: "18:00", label: "Today, 6:00 PM" },
      {
        date: new Date(Date.now() + 86400000).toISOString().split("T")[0],
        time: "09:30",
        label: "Tomorrow, 9:30 AM",
      },
    ],
    nextAvailable: "today",
    rating: 4.9,
    reviewCount: 348,
    yearsExperience: 18,
    qualifications: ["MD (Pediatrics)", "DCH", "Fellowship Neonatology (AIIMS)"],
    hospital: "Belle Vue Clinic",
    department: "Pediatrics & Neonatology",
    keywords: [
      "child", "children", "infant", "baby", "newborn", "toddler",
      "fever", "child fever", "vaccination", "growth", "development",
      "cough in children", "diarrhea in children", "rash in child",
      "pediatric", "neonatal", "jaundice in newborn", "feeding",
    ],
    urgencyCapable: true,
    emergencySpecialist: false,
    bio: "Dr. Biswas is a senior pediatrician and neonatologist with 18 years of experience managing complex newborn care and childhood illnesses.",
    consultationFee: 700,
    acceptsWalkIn: true,
  },
];

// ---------------------------------------------------------------------------
// In-memory lookup maps — O(1) access
// ---------------------------------------------------------------------------

export const DOCTOR_BY_ID = new Map<string, Doctor>(DOCTORS.map((d) => [d.id, d]));
